return {
  { name = 'add-dir', desc = 'Add additional working directories', hint = '<path>' },
  { name = 'agents', desc = 'Manage custom AI subagents' },
  { name = 'background', desc = 'Send this session to the background and free the terminal', hint = '[prompt]' },
  { name = 'bashes', desc = 'View and manage everything running in the background' },
  { name = 'bg', desc = 'Send this session to the background and free the terminal', hint = '[prompt]' },
  { name = 'bug', desc = 'Submit feedback, report a bug, or share your conversation', hint = '[report]' },
  { name = 'clear', desc = 'Clear conversation history' },
  { name = 'compact', desc = 'Compact conversation', hint = '[focus]' },
  { name = 'config', desc = 'Open Settings' },
  { name = 'context', desc = 'Visualize context usage' },
  { name = 'cost', desc = 'Show session cost, plan usage, and activity stats' },
  { name = 'doctor', desc = 'Check installation health' },
  { name = 'exit', desc = 'Exit the REPL' },
  { name = 'export', desc = 'Export conversation', hint = '[filename]' },
  { name = 'help', desc = 'Get usage help' },
  { name = 'hooks', desc = 'Manage hooks' },
  { name = 'ide', desc = 'Manage IDE integrations' },
  { name = 'init', desc = 'Initialize CLAUDE.md' },
  { name = 'install-github-app', desc = 'Setup GitHub Actions' },
  { name = 'login', desc = 'Switch accounts' },
  { name = 'logout', desc = 'Sign out' },
  { name = 'mcp', desc = 'Manage MCP servers' },
  { name = 'memory', desc = 'Edit CLAUDE.md' },
  { name = 'model', desc = 'Select AI model', hint = '[model]' },
  { name = 'permissions', desc = 'View permissions' },
  { name = 'plan', desc = 'Enter plan mode' },
  { name = 'plugin', desc = 'Manage plugins' },
  { name = 'privacy-settings', desc = 'Privacy settings' },
  { name = 'release-notes', desc = 'View release notes' },
  { name = 'rename', desc = 'Rename session', hint = '<name>' },
  { name = 'remote-env', desc = 'Configure remote env' },
  { name = 'resume', desc = 'Resume conversation', hint = '[session]' },
  { name = 'review', desc = 'Request code review' },
  { name = 'rewind', desc = 'Rewind conversation' },
  { name = 'sandbox', desc = 'Enable sandbox' },
  { name = 'security-review', desc = 'Security review' },
  { name = 'stats', desc = 'Show session cost, plan usage, and activity stats' },
  { name = 'status', desc = 'Show status' },
  { name = 'statusline', desc = 'Setup statusline' },
  { name = 'tasks', desc = 'View and manage everything running in the background' },
  { name = 'teleport', desc = 'Resume remote session', hint = '<session-id>' },
  { name = 'terminal-setup', desc = 'Install keybindings' },
  { name = 'theme', desc = 'Change theme' },
  { name = 'usage', desc = 'Show usage limits' },
  -- built-in skills (not discoverable from disk)
  { name = 'update-config', desc = 'Configure Claude Code settings', skill = true },
  { name = 'keybindings-help', desc = 'Customize keyboard shortcuts', skill = true },
  { name = 'simplify', desc = 'Review code for quality and simplify', skill = true },
  { name = 'loop', desc = 'Run a command on a recurring interval', hint = '[interval] [command]', skill = true },
  { name = 'schedule', desc = 'Manage scheduled remote agents', skill = true },
  { name = 'claude-api', desc = 'Build Claude API / Anthropic SDK apps', skill = true },
  { name = 'deep-research', desc = 'Fan-out research with a cited report', hint = '[topic]', skill = true },
  { name = 'code-review', desc = 'Review the current diff for bugs and cleanups', hint = '[effort]', skill = true },
  { name = 'verify', desc = 'Verify a change works by running the app', skill = true },
  { name = 'run', desc = 'Launch and drive this project app', skill = true },
  { name = 'fewer-permission-prompts', desc = 'Add an allowlist to reduce permission prompts', skill = true },
}
